server:
  servlet:
    context-path: /
  undertow:
    threads:
      io: 4
      worker: 16
    buffer-size: 1024
    direct-buffers: true
  port: 10022
spring:
  application:
    name: gift-code
  mvc:
    view:
      suffix: .html
      prefix: templates/
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
  datasource:
    url: jdbc:h2:file:~/.h2/giftcodedb
    driver-class-name: org.h2.Driver
    schema: classpath:schema-h2.sql
    hikari:
      pool-name: giftcode-pool
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mappers/*.xml

